<div class="flex-container">
  <div class="row">
    <div class="col">
      <div class="slider">
        <ul>
          <li><img src="img/casa1.jpg" alt="casa1" width="700" height="500"></li>
          <li><img src="img/casa2.jpg" alt="casa2" width="700" height="500"></li>
          <li><img src="img/casa3.jpg" alt="casa3" width="700" height="500"></li>
        </ul>
      </div>
      <center><h1>Recomendados para ti</h1></center>
      <section class="contenido wrapper">
        <h1>Mis Rentas</h1>
        <br>
        <p><b><a href="#">Juan José González Nierto</a></b></p>
        <p>>Av Ejército Nacional 843, Granada, 11520 Ciudad de México, CDMX</p>
        <br>
         <p><b><a href="#">Rodrigo Talavera Vazquez</a></b></p>
        <p>>Carretera San Luis Potosí Querétaro 12401, 76127 Qro.</p>
        <br>
      </section>
    </div>
  </div>
</div>
