<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 mx-auto bg-primary">
      <form class="col-12" action="php/inmueble.php?action=update" enctype="multipart/form-data" method="post">
          <input type="hidden" name="id" value="1">
          <div class="form-group" id="user-group">
              <input type="text" class="form-control" placeholder="Num Habitaciones" name="numRooms" />
          </div>
          <div class="form-group" id="user-group">
              <input type="text" class="form-control" placeholder="Num Baños" name="numBathrooms" />
          </div>
          <div class="form-group" id="user-group">
              <input type="text" class="form-control" placeholder="Mascotas permitidas" name="pets" />
          </div>
          <div class="form-group" id="user-group">
              <input type="text" class="form-control" placeholder="Capacidad maxima" name="maxCapacity" />
          </div>
          <div class="form-group" id="user-group">
              <input type="text" class="form-control" placeholder="Costo por mes" name="cost" />
          </div>
          <div class="form-group" id="user-group">
              <input type="text" class="form-control" placeholder="Calle" name="street" />
          </div>
          <div class="form-group" id="user-group">
              <input type="text" class="form-control" placeholder="Numero exterior" name="extNumber" />
          </div>
          <div class="form-group" id="user-group">
              <input type="text" class="form-control" placeholder="Colonia" name="neighborhood" />
          </div>
          <div class="form-group" id="user-group">
              <input type="text" class="form-control" placeholder="Estado" name="city" />
          </div>
          <div class="form-group" id="user-group">
              <input type="file" class="form-control" placeholder="Imagen" name="image" />
          </div>
          <button id="Blogin" type="submit" class="btn btn-success"><i class="fas fa-sign-in-alt"></i>  Publicar </button>
      </form>
    </div>
  </div>
</div>
