<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Iniciar Sesión</title>
  <link rel="stylesheet" href="../css/style.css">
  <style>
      body{
          background: url("../img/fondo2.png");
      }
  </style>
</head>

  <body>
  <div class="contenedor-form">
    <div class="toggle">
      <span><a href="../indexUser.php">Volver</a></span>
    </div>
    <div class="formulario">
      <h2>Publicar Inmueble</h2>
      <form action="../php/inmueble.php?action=add" enctype="multipart/form-data" method="post">
        <input type="text" placeholder="Numero de habitaciones" name="numRooms" required>
        <input type="text" placeholder="Numero de baños" name="numBathrooms" required>
        <br>
        <span>Mascotas permitidas:</span>
        <br>
        <label for="mascotasSi">Si</label>
        <input type="radio" id="mascotasSi" name="pets" value="1">
        <label for="mascotasNo">No</label>
        <input type="radio" id="mascotasNo" name="pets" value="0">
        <br>
        <input type="text" placeholder="Capacidad máxima" name="maxCapacity" required>
        <input type="text" placeholder="Costo por mes" name="cost" required>
        <input type="text" placeholder="Calle" name="street" required>
        <input type="text" placeholder="Número exterior" name="extNumber" required>
        <input type="text" placeholder="Colonia" name="neighborhood" required>
        <input type="text" placeholder="Estado" name="city" required>
        <input type="file" placeholder="Imagen" name="image" required>
        <input type="submit" value="Publicar">
      </form>
    </div>
  </div>
</body>
</html>
