<div class="fluid-container">
  <br>
  <br>
  <div class="row">
    <div class="col text-center">
        <br>
        <h1>Inmuebles</h1>
        <div class="row">
          <div class="col-10 mx-auto">
            <div class="row">
              <div class="card-deck" id="catalogoInmuebles">
                <!-- Catalogo de inmuebles -->
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

<script src="js/inmueble.js" type="text/javascript"></script>
<script>solicitarCatalogoInmuebles();</script>
