<div class="mt-2"></div>
<footer style="background-color: #2f4561;">
  <ul class="list-unstyled list-inline text-center text-white">
      <li class="list-inline-item">
          <a class="btn-floating btn-fb mx-1" href="#">
              <i class="fab fa-facebook-f"> </i>
          </a>
      </li>
      <li class="list-inline-item">
          <a class="btn-floating btn-tw mx-1" href="#">
              <i class="fab fa-twitter"> </i>
          </a>
      </li>
      <li class="list-inline-item">
          <a class="btn-floating btn-li mx-1" href="#">
              <i class="fab fa-instagram"> </i>
          </a>
      </li>
      <li class="list-inline-item">
          <a class="btn-floating btn-dribbble mx-1" href="#">
              <i class="fab fa-pinterest"> </i>
          </a>
      </li>
  </ul>
  <div class="footer-copyright text-center py-3 text-light">© 2020 Copyright:
      <a href="https://mdbootstrap.com/">youridealhome.com</a>
  </div>
</footer>
<!-- Footer -->
<!-- <script type="text/javascript" src="js/script.js"></script> -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>
