<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Your Ideal Home</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Los iconos tipo Solid de Fontawesome-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
  <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
  <!-- FRAMEWORK BOOTSTRAP para el estilo de la pagina-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <!-- Nuestro css-->
  <!-- <link rel="stylesheet" type="text/css" href="css/style.css">
  <link rel="stylesheet" type="text/css" href="css/estilos2.css"> -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:100,300,500" rel="stylesheet">

</head>

<!-- El cierre del etiqueta body si encuentra en el footer -->
<body>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #2f4561;">
      <a class="navbar-brand" href="?page=home">
          <img src="img/logo.png" width="400" height="65" alt="logo">
      </a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <class class="navbar-nav mr-auto">
              <li class="nav-item active">
                  <a class="nav-link" href="?page=home">Inicio <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="?page=inmuebles">Inmuebles</a>
              </li>
          </class>
          <div class="navbar-nav mr-4">
              <li class="nav-item">
                  <a class="btn btn-primary" href="?page=nuevoInmueble"><i class="fas fa-sign-out-alt"></i>   Publicar inmueble</a>
              </li>
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i>   <?php echo $_SESSION['username']; ?></a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="?page=misPublicaciones">Mis publicaciones</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="php/logout.php">Cerrar sesión</a>
                  </div>
              </li>
          </div>
      </div>
  </nav>
