<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Your Ideal Home</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Los iconos tipo Solid de Fontawesome-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
  <script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
  <!-- FRAMEWORK BOOTSTRAP para el estilo de la pagina-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <!-- Nuestro css-->
  <link rel="stylesheet" type="text/css" href="css/style.css">
  <link rel="stylesheet" type="text/css" href="css/estilos2.css">
  <link href="https://fonts.googleapis.com/css?family=Poppins:100,300,500" rel="stylesheet">

</head>

<!-- El cierre del etiqueta body si encuentra en el footer -->
<body>
  <header>
    <section class="wrapper">
    	<nav>
        <ul>
          <li><a href="?page=home">Inicio</a></li>
  	      <li><a href="?page=nuevoInmueble">Publicar</a></li>
  	      <li><img src="img/logo.png" alt="logo" width="500" height="90"></li>
          <li><a href="?page=inmuebles">Buscar</a></li>
          <li><a href="php/logout.php">Salir</a></li>
        </ul>
    	</nav>
    </section>
  </header>
